---
# tasks file for ansible-samba
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: samba_groups.yml
  when: samba_groups is defined

- import_tasks: samba_users.yml
  when: samba_users is defined

- import_tasks: create_shares.yml
  when: samba_shares is defined

- import_tasks: config_samba.yml

- import_tasks: create_domain.yml
  when:
    - samba_create_domain_controller|bool

- import_tasks: join_domain.yml
  when:
    - samba_create_domain_controller|bool
    - samba_domain_controllers_group is defined
    - inventory_hostname != samba_primary_domain_controller

- import_tasks: domain_users.yml
  tags:
    - samba_domain_account_management
    - samba_domain_users
  when:
    - samba_create_domain_users is defined
    - samba_create_domain_users|bool
    - samba_domain_controllers_group is defined
    - inventory_hostname == samba_primary_domain_controller

- import_tasks: domain_groups.yml
  tags:
    - samba_domain_account_management
    - samba_domain_groups
  when:
    - samba_create_domain_groups is defined
    - samba_create_domain_groups|bool
    - samba_domain_controllers_group is defined
    - inventory_hostname == samba_primary_domain_controller
